# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jenny's Digital Brain
email: jenny@jennybrain.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Jenny's second brain! She is working on it right now, so it can be changed pretty often.
baseurl: ""
url: "http://jennybrain.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  jenniverse

# Build settings
remote_theme: samarsault/texture

plugins:
  - jekyll-feed

texture:
  style: purple
  title: Jenny's Digital Brain
  tagline: Student
  date_format: "%b %-d, %Y"
  showNav: true

  social_links:
    twitter: 
    github:  jenniverse
    linkedIn: